remote_theme: abhinavs/moonwalk
title: DevGreen News
description: Portal independente de notícias sobre sustentabilidade e economia circular
url: "https://ambisocial.github.io"
baseurl: "/devgreen-news"
author: Redação DevGreen News
email: contato@devgreen-news.com
lang: pt-BR
timezone: America/Sao_Paulo
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
markdown: kramdown
highlighter: rouge
